사용자 조회, 수정 서비스 테스트 코드 작성
youngjinmo/BomStart_Ex01 pull request #11
Opened 2021-03-22 13:52 UTC by zaragit

사용자 조회, 수정 테스트 코드 작성했습니다.
말씀해주신 update 오류랑 select에 있는 오류까지 수정했습니다.
Controller 테스트 코드 작성해 보다가 시간이 늦어질 것 같아서 지금까지 작성한 코드 먼저 PR 합니다.

2021-03-22 14:23 UTC, youngjinmo commented
확인했습니다! BeforeEach와 AfterEach 작성하신것 감사합니다 ㅎㅎ
Merge해도 충분한 코드라고 생각됩니다만 최근에 배운 AssertAll을 적용할 수 있는 코드가 보여서 코멘트 남겨드렸으니 확인부탁드립니다!

2021-03-23 00:33 UTC, zaragit commented
제 화면에서는 comment가 아직 안보이는데 pending 상태인지 확인 부탁드립니다.

2021-03-23 00:55 UTC, youngjinmo requested changes
아 이렇게 리퀘스트 해야하는군요..! 죄송합니다..ㅎㅎ
확인 부탁드립니다!

2021-03-23 00:55 UTC, youngjinmo commented on src/test/java/com/bomstart/tobyspring/user/service/UserServiceTest.java
> +        assertEquals(user1.getPassword(), actual.getPassword());
최근에 테스트 코드 작성법을 하나씩 배우고 있는데, 얼마전 배운걸 하나 소개해드리고 싶습니다!
하나의 테스트 메서드에서 여러개의 assert를 쓸 경우에 AssertAll을 사용하는게 좋다고 하더라구요.

AssertAll을 쓰는 이유는 위의 코드의 경우 만약 `user1.getId()` 를 검증하는 과정에서 테스트 결과가 fail일 경우 그 다음 `user1.getName()` 을 검증하는 테스트 코드가 작동하지 않는다고 하더라구요. 
그러나 AssertAll의 경우 모든 테스트 결과를 확인할 수 있습니다!

잘 정리해둔 글이 있어서 공유합니다 ㅎㅎ
[[JUnit5] Assertion 메소드(assertTrue, assertEquals, assertAll 등)](https://sas-study.tistory.com/316)

2021-03-23 00:55 UTC, youngjinmo commented on src/test/java/com/bomstart/tobyspring/user/service/UserServiceTest.java
> +        assertEquals(actual.size(), start + 3); // then
이 코드도 AssertAll로 대체할 수 있을것 같습니다!

2021-03-23 01:52 UTC, zaragit commented on src/test/java/com/bomstart/tobyspring/user/service/UserServiceTest.java
> +        assertEquals(user1.getPassword(), actual.getPassword());
넵 AssertAll 말씀해 주셔서 찾아보려고 했었는데 자료 공유까지!!😁 감사합니다.
영진님이 피드백 주신 대로 assertAll로 처리해야겠네요!

2021-03-23 01:52 UTC, zaragit commented on src/test/java/com/bomstart/tobyspring/user/service/UserServiceTest.java
> +        assertEquals(actual.size(), start + 3); // then
넵! 해당 코드도 assertAll로 작업하겠습니다.

2021-03-23 01:56 UTC, zaragit commented
코드리뷰 감사합니다!! 
리뷰해 주신 내용 대로 assertThat(actual).usingRecursiveComparison().isEqualTo(user1); 이 부분도 assertAll로 수정하겠습니다.
위에 내용과 비슷한 이유로 찾아서 작업했었는데 지금 보니깐 assertj에 assertThat이었네요..

2021-03-23 11:24 UTC, zaragit commented
영진님 assertAll 사용해서 코드 개선해 봤습니다. 확인 부탁드립니다!

2021-03-23 11:37 UTC, youngjinmo commented on src/test/java/com/bomstart/tobyspring/user/service/UserServiceTest.java
> -        assertThat(actual).usingRecursiveComparison().isEqualTo(user1);
제가 잘몰라서 그러는데, `usingRecursiveComparison()` 메서드는 어떤 역할을 하는 메서드인가요?

2021-03-23 11:39 UTC, merged

2021-03-23 11:39 UTC, youngjinmo commented
먼저 끝내주셨군요..! 저는 서비스까지 일단 하긴했는데, 컨트롤러에서 Mock을 이용해서 테스트하는것에 익숙지 않아서 찾아보는데 시간이 좀 걸리네요...ㅎㅎ
요청하신 PR은 Merge해도 될 것 같아서 Merge 하겠습니다! 고생하셨습니다!!